Plans実装
shinonome-inc/hikarix-frontend-basic-last-assignment pull request #13
Opened 2023-02-07 12:13 UTC by Hikari-Tanaka-pikka

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](chromatic上の該当ページへのリンクを貼る)

2023-02-09 04:03 UTC, kogaokumura commented
・plan同士の幅が違うので修正お願いします。
・文字のフォントを指定通りに変更お願いします。
・真ん中のplanのborderをもう少し細くするようにしてください。

2023-02-10 14:39 UTC, Hikari-Tanaka-pikka commented
> ・plan同士の幅が違うので修正お願いします。 ・文字のフォントを指定通りに変更お願いします。 ・真ん中のplanのborderをもう少し細くするようにしてください。
対応しました!

4efc01e5a6c534bc5e0b437df766c50a6229d355

2023-02-10 22:23 UTC, AyumuTaoka commented on src/components/organisms/plans/plans.scss
> +    display: none;
こちらの`display: none;`はどういった意図でつけているのでしょうか？
検証ツールではこれの存在を確認できませんでした。もし不要であれば消しておいてください。

2023-02-11 12:17 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +    display: none;
対応しました!

ac43676e57197a129390b2b95c493e91248e7e62

2023-02-11 13:57 UTC, higashiji2000 requested changes
基本的に見た目はOKです！
`.container` のスタイルはできれば上書きしない方向で修正お願いします 🍔

2023-02-11 13:57 UTC, Higashiji commented on src/components/organisms/plans/plans.scss
> +  margin-bottom: 100px;
```suggestion
  margin: 0 auto 100px;
```
これでもいけそうです！

2023-02-11 13:57 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +}
.container に対してスタイルを設定してしまうと、サイト全体に影響してしまうので避けたほうがいいかもです。
書くとしたら `.container.organisms-plans` みたいな感じに詳細なセレクタを使って、影響範囲を狭めるようにしましょう。

2023-02-11 13:57 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +    width: calc(calc(100% - 60px) / 3);
ここはwidthを指定するのではなく `flex` プロパティと `gap` を使って実装できるとより良いと思います。
現状でも見た目に問題ないので、修正必須ではありません 🙆‍♂️ 

[flex参考](https://zero-plus.io/media/css-flex-shorthand/)
[gap参考](https://ics.media/entry/210628/)

2023-02-12 09:01 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +}
対応しました!

ac43676e57197a129390b2b95c493e91248e7e62

2023-02-12 09:03 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +    width: calc(calc(100% - 60px) / 3);
対応しました!

c9d5fa7213f17cea618e5ff8e6fcefc13849d11a

2023-02-16 02:02 UTC, higashiji2000 requested changes
見た目が崩れているので確認お願いします！
![image](https://user-images.githubusercontent.com/83479175/219246561-810e933a-062e-424d-9c72-c26f643db733.png)

2023-02-16 02:02 UTC, Higashiji commented on src/components/organisms/plans/plans.scss
> +  padding-right: 0;
下方向の余白以外は `.container` のスタイルを活用するようにしましょう！

2023-02-16 02:02 UTC, Higashiji commented on src/components/organisms/plans/plans.scss
> +}
```suggestion
```
ここの記述は不要だと思います！

2023-02-16 02:02 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +  gap: 15px;
![image](https://user-images.githubusercontent.com/83479175/219248166-fa95f6e5-9909-4a18-829f-808be999ad70.png)
lg以上のときの、 message~plans~buttonそれぞれの間隔が広すぎる感じがするので、figma準拠で修正お願いします！

2023-02-18 04:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +  gap: 15px;
@higashiji2000 
対応しました!

fd1453efe2f4af01a2ccf5da66d9e5d43ad054e8

2023-02-18 04:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +}
@higashiji2000 
対応しました!

fd1453efe2f4af01a2ccf5da66d9e5d43ad054e8

2023-02-18 04:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/plans/plans.scss
> +  padding-right: 0;
@higashiji2000 
対応しました!

fd1453efe2f4af01a2ccf5da66d9e5d43ad054e8

2023-02-18 05:10 UTC, higashiji2000 approved these changes

2023-02-18 05:10 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +    grid-template-columns: auto auto auto;
```suggestion
    grid-template-columns: 1fr 1fr 1fr;
```
単位としてfrのほうがよく使うイメージがあるので、こちらも把握しておきましょう！
参考：https://kumonosublog.com/coding/css/grid_layout_fr_auto/

2023-02-18 05:10 UTC, merged