Footer実装
shinonome-inc/hikarix-frontend-basic-last-assignment pull request #14
Opened 2023-02-07 12:38 UTC by Hikari-Tanaka-pikka

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[https://www.chromatic.com/build?appId=62e56f70bf1df6d4e303b869&number=89](chromatic上の該当ページへのリンクを貼る)

2023-02-09 06:17 UTC, kogaokumura commented
・smallのとき「定休日 / 不定休 」が下に回っているのでそこを修正お願いします。
・font-familyをfigma通りにお願いします。

2023-02-09 23:46 UTC, Hikari-Tanaka-pikka commented
> ・smallのとき「定休日 / 不定休 」が下に回っているのでそこを修正お願いします。 ・font-familyをfigma通りにお願いします。

対応しました!
a3abd221fb2af4af7b9d352efb33ffade9fe9327

2023-02-10 14:10 UTC, kogaokumura commented
smallのときにiconの下に余白がなくなってしまっているので、そこだけ修正お願いします。

2023-02-10 14:23 UTC, Hikari-Tanaka-pikka commented
> smallのときにiconの下に余白がなくなってしまっているので、そこだけ修正お願いします。 ![image](https://user-images.githubusercontent.com/107789098/218112512-eaf53e5d-40e2-4b2a-86a9-371ca45c5e0d.png)

d2eb82c0ec2bde5768cf72c7a70fa4745abe48af

2023-02-10 14:24 UTC, Hikari-Tanaka-pikka commented
> > smallのときにiconの下に余白がなくなってしまっているので、そこだけ修正お願いします。 ![image](https://user-images.githubusercontent.com/107789098/218112512-eaf53e5d-40e2-4b2a-86a9-371ca45c5e0d.png)
> 
対応しました!
> [d2eb82c](https://github.com/shinonome-inc/hikarix-frontend-basic-last-assignment/commit/d2eb82c0ec2bde5768cf72c7a70fa4745abe48af)

2023-02-11 14:48 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/218264301-f416e467-f4dd-4495-b8c6-984e0678c6c9.png)
白い部分と灰色の部分の間にborderがあるので、こちら再現お願いします 🐰

2023-02-11 14:48 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +<div class="contact-wrapper text-center">
単一のコンポーネントとして扱いたいので、このファイル全体を `footer` 要素で囲んでください。
scssの方にも入れ子構造を反映させるようにお願いします。

2023-02-12 08:40 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/footer/footer.html
> +<div class="contact-wrapper text-center">
対応しました!

2023-02-12 08:48 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/footer/footer.html
> +<div class="contact-wrapper text-center">
> ![image](https://user-images.githubusercontent.com/83479175/218264301-f416e467-f4dd-4495-b8c6-984e0678c6c9.png) 白い部分と灰色の部分の間にborderがあるので、こちら再現お願いします 🐰

対応しました!
cbacdfd8b5704c8b9a3ea046d001780b2a035020

2023-02-16 01:34 UTC, higashiji2000 approved these changes
LGTMです🙈

2023-02-16 01:34 UTC, merged