organisms / news実装
shinonome-inc/hikarix-frontend-basic-last-assignment pull request #8
Opened 2022-11-22 09:33 UTC by Hikari-Tanaka-pikka

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](chromatic上の該当ページへのリンクを貼る)

2022-11-23 02:23 UTC, moe-backend commented
骨組みができていて良いです！！
・記事のフォントを修正しましょう
・...で省略するのは1行で収まりきらないときなので横幅が広いときは省略されないようにしましょう
・お知らせ一覧>の位置は右端になります

2022-12-06 13:50 UTC, tomu-fujikawa reviewed
もうかなりいい感じです！✨

修正点
・Figmaのtemplates/news-eventsのnewsの部分を見ていただくと、mdのときNewsのfontsizeが20pxとなっているのでそうなるようにしてください！
・「日付」と「お知らせ一覧」のfontfamilyがfigmaと異なっています！
・「お知らせ一覧」の上のmarginがfigmaと異なっています！

2022-12-08 15:19 UTC, SakaueYae commented on src/components/molecules/news-and-events-title/news-and-events-title.scss
> +    @media (man-width: $breakpoint-lg) {
タイプミスです
×man-width
〇max-width

また、figmaのコメントによると「作成済みのmolecules/news-and-events-title の breakpointがfigmaと違う場合がありますが、一旦ここは無視で大丈夫」とのことなので、削除してもらっても大丈夫かもしれません。

2022-12-08 15:19 UTC, SakaueYae commented on src/components/organisms/news/news.html
> +  <a href="#" class="news-and-events-more">お知らせ一覧<i class="fas fa-chevron-right"></i></a>
![image](https://user-images.githubusercontent.com/101164626/206476603-8834beab-c15e-424d-a60e-709fde08cc89.png)
記事のブロックとnews-and-events-moreの間の余白が小さいため、修正お願いします！

2022-12-08 15:19 UTC, SakaueYae commented on src/components/organisms/news/news.scss
> +    .date{
ここのfont-familyの修正をお願いします！

2022-12-08 15:19 UTC, SakaueYae commented on src/components/organisms/news/news.html
> +    <p class="news-caption">
`.news-caption`はそれぞれの記事の見出しなので、h3タグなどを使ってあげた方が良いと思います！

2022-12-08 15:19 UTC, SakaueYae commented on src/components/organisms/news/news.scss
> +        color: $orange_bistre;
0.2秒 ease でフォントの色が変わるように指示されているため、修正をお願いします！

2022-12-08 15:19 UTC, SakaueYae commented on src/components/organisms/news/news.html
> +  <article class="news-card">
1つ1つの記事をリンクにしてクリックできるようにしていただきたいため、タグの追加をして修正してみてください！

2023-01-13 03:10 UTC, tomu-fujikawa reviewed
コメントしました！✨

2023-01-13 03:10 UTC, tomu-fujikawa commented on src/components/organisms/news/news.html
> +    <h3 class="news-card" href="#">
`<h3>`からhrefを消して`<h3>`を`<a>`で囲って`<a>`にhrefをあげよう！（`<a>`以外で画面遷移させようとしたらonClick属性が必要になってjavascriptのコードを書くことになるので）
これは全部のnews-cardでやりましょう！(`<a>`で囲うから`text-decoration: none;`が必要になってくるかも)

あとhタグで囲っている影響で`font-weight`の指定が必要になっています！

2023-01-13 03:10 UTC, tomu-fujikawa commented on src/components/organisms/news/news.html
> +        ブックカフェ・コワーキング系サイト向けテーマ「Switch」をリリースしました。
上の方で画面遷移するようにしているのでここでは`<a>`は必要なくなるため`<p>`か`<h>`を使いましょう！(`<h>`を使うのならfont-weightに注意してください)

2023-01-13 03:10 UTC, tomu-fujikawa commented on src/stories/organisms-news.stories.js
> +export const News = () => Item_News;
最終行は空行にするようにお願いします！（空行じゃないと動かないコードも存在するので）

2023-01-13 03:10 UTC, tomu-fujikawa commented on src/components/organisms/news/news.html
> +  <a href="#" class="news-and-events-more">お知らせ一覧<i class="fas fa-chevron-right"></i></a>
お知らせ一覧の上の余白の修正お願いします！

2023-01-13 15:07 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.html
> +    <h3 class="news-card" href="#">
h3タグをaタグで囲むと、borderが消えてしまうのですが、この現象を解決できません。どうすればいいでしょうか

2023-01-13 15:11 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.html
> +  <a href="#" class="news-and-events-more">お知らせ一覧<i class="fas fa-chevron-right"></i></a>
@tomu-fujikawa 

修正しました!

1f3b03accc109f6d01de3c447277ebc4c4846e21

2023-01-13 15:11 UTC, Hikari-Tanaka-pikka commented on src/stories/organisms-news.stories.js
> +export const News = () => Item_News;
@tomu-fujikawa 

修正しました!

1f3b03accc109f6d01de3c447277ebc4c4846e21

2023-01-13 15:11 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.html
> +        ブックカフェ・コワーキング系サイト向けテーマ「Switch」をリリースしました。
@tomu-fujikawa 

修正しました!

1f3b03accc109f6d01de3c447277ebc4c4846e21

2023-01-14 14:04 UTC, tomu-fujikawa commented on src/components/organisms/news/news.html
> +    <h3 class="news-card" href="#">
last-of-typeが全ての`<h3>`(news-cardクラス)に効いてしまっているためこのようなことになっています！
last-of-typeは「同じ要素名を持つ最後の子要素に適用に適用される」ため、`<h3>`(news-cardクラス)を`<a>`で囲むと`<h3>`(news-cardクラス)の親要素の`<a>`から見て囲んだ`<h3>`(news-cardクラス)が最後の子要素になってしまうという形です。
参考ページ↓
https://www.zunouissiki.com/how-to-use-first-of-type-last-of-type/#i-2

2023-01-14 14:09 UTC, tomu-fujikawa commented on src/components/organisms/news/news.html
> +    </h3>
`font-weight`の指定とホバーした際の下線の削除をお願いします！

2023-01-22 11:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.html
> +    </h3>
@tomu-fujikawa 
修正しました!

3845eab370c8f48c7362854ea4f9766e0ce691fd

2023-01-23 06:08 UTC, MoAI522 commented on src/components/molecules/news-and-events-title/news-and-events-title.scss
> +    @media (man-width: $breakpoint-lg) {
これ直ってないっす

2023-01-23 06:08 UTC, MoAI522 commented on src/components/organisms/news/news.scss
> +}
h2といきなり指定してしまうと、ページ内の全てのh2に影響してしまいます。
実際にそうしたい場合はutilities等の、共有のスタイルであることが明示的であるところに書くべきですし、今回このコンポーネントだけの話であるならばちゃんとクラスの指定を追加しましょう

2023-01-23 06:08 UTC, MoAI522 commented on src/components/organisms/news/news.html
> +<div class="news-and-events-title">
コンポーネントとして独立していることを意味的に表すことや、スタイルの指定が予期せず上書きされることを防止するために、html全体をさらにdivで囲って、organisms/newsだと分かるようなクラス名をつけましょう。
scssの方も、そのクラスの配下にあるものにしかスタイルが適用されないよう、入れ子にして書きましょう。

2023-01-23 06:08 UTC, MoAI522 commented on src/components/organisms/news/news.scss
> +.news-list{
prettierが効いていない香りがするので、設定の確認をお願いします。

2023-01-30 11:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.html
> +<div class="news-and-events-title">
@MoAI522 
修正しました!

b28070e2514c9f5908b78a75eeea09193c12ac25

2023-01-30 11:23 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.scss
> +}
@MoAI522 
修正しました!

b28070e2514c9f5908b78a75eeea09193c12ac25

2023-02-07 09:41 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.scss
> +.news-list{
対応しました!

b28070e2514c9f5908b78a75eeea09193c12ac25

2023-02-12 14:32 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/218317170-80df93c7-a58d-45cc-a379-807d8d0162a6.png)
横線が消えているので確認お願いします！

2023-02-12 14:32 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +}
このようなユーティリティ的なクラスは、 `utilities.scss` の方に記述するようにしましょう。
（そもそも `utilities.scss` で body に対してゴシック体の指定をしているので、継承によりそれぞれの要素に対しゴシック体の指定を追加でする必要は基本的にありません！）

2023-02-12 14:32 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +      font-family: $fontfamily-gothic;
この辺のフォントの設定もなくて大丈夫です！

2023-02-14 09:40 UTC, Hikari-Tanaka-pikka commented
> ![image](https://user-images.githubusercontent.com/83479175/218317170-80df93c7-a58d-45cc-a379-807d8d0162a6.png) 横線が消えているので確認お願いします！

対応しました!
183189bffb2e626de46231e3f67e2ed1f25975f7

2023-02-14 09:41 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.scss
> +}
対応しました!

183189bffb2e626de46231e3f67e2ed1f25975f7

2023-02-14 09:41 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/news/news.scss
> +      font-family: $fontfamily-gothic;
対応しました!

183189bffb2e626de46231e3f67e2ed1f25975f7

2023-02-15 07:55 UTC, MoAI522 approved these changes
LGTM

2023-02-15 07:55 UTC, merged