ヘッダー実装
shinonome-inc/hikarix-frontend-basic-last-assignment pull request #9
Opened 2023-01-12 23:55 UTC by Hikari-Tanaka-pikka

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](chromatic上の該当ページへのリンクを貼る)

2023-01-13 03:38 UTC, tomu-fujikawa reviewed
最難関の課題なのにかなり書けています！✨

修正点
・バーガーアイコンを押したあとにバーガーアイコンの周りに白い枠が生じるのでなくしてください
・全体的に`fontfamily`の修正お願いします

2023-01-13 03:38 UTC, tomu-fujikawa commented on src/components/_reset.scss
>  }
最終行は空行でお願いします

2023-01-13 03:38 UTC, tomu-fujikawa commented on src/components/atoms/header/dropdown-menu.scss
> +  }
extraLarge以上のときにホバーで色が変わるように修正お願いします！
lg以下のときにホバーするとアンダーラインと文字色の変化が生じるので修正お願いします！

2023-01-13 15:59 UTC, Hikari-Tanaka-pikka commented
> 最難関の課題なのにかなり書けています！✨
> 
> 修正点 ・バーガーアイコンを押したあとにバーガーアイコンの周りに白い枠が生じるのでなくしてください ・全体的に`fontfamily`の修正お願いします

@tomu-fujikawa 
修正しました!

3be4a3d95c72343b85d748baee1d394e047d8f07

2023-01-13 15:59 UTC, Hikari-Tanaka-pikka commented on src/components/atoms/header/dropdown-menu.scss
> +  }
@tomu-fujikawa 
修正しました!

3be4a3d95c72343b85d748baee1d394e047d8f07

2023-01-13 15:59 UTC, Hikari-Tanaka-pikka commented on src/components/_reset.scss
>  }
@tomu-fujikawa 
修正しました!

3be4a3d95c72343b85d748baee1d394e047d8f07

2023-01-14 14:50 UTC, tomu-fujikawa commented on src/components/organisms/header/header.html
> +  <img src="../../../img/logo.png" alt="" class="main-logo">
Figmaに「Switchのロゴをクリックするとtopページに戻ってきます」とあるので2行目は`<a herf="#">`で囲みましょう！

2023-01-15 12:59 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/212541782-49ff5419-fc25-435d-8de8-9c39776789b1.png)
開いた状態で sm → xl に画面幅を変更すると、開いたメニューが残りっぱなしになってしまうので確認お願いします！

現在xlとそれ以下で別の要素でメニューを表現していますが、
保守性を考えると共通化してもいいのかなと思います。
難しかったら必須とはしません！

---

![image](https://user-images.githubusercontent.com/83479175/212541905-36685f22-fbf5-4fb8-acc7-26e0246961a3.png)

![image](https://user-images.githubusercontent.com/83479175/212541914-8339e86d-786e-4f53-bfe2-71165cb677f7.png)

上現在、下figmaです。
xl時、右端の余白が大きすぎる気がするので確認お願いします 🙌

2023-01-15 16:54 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/header/header.html
> +  <img src="../../../img/logo.png" alt="" class="main-logo">
修正しました!

7a5148e84b77961343352a88de7c2d6fbd6800ac

2023-01-15 16:55 UTC, Hikari-Tanaka-pikka commented
> ![image](https://user-images.githubusercontent.com/83479175/212541782-49ff5419-fc25-435d-8de8-9c39776789b1.png) 開いた状態で sm → xl に画面幅を変更すると、開いたメニューが残りっぱなしになってしまうので確認お願いします！
> 
> 現在xlとそれ以下で別の要素でメニューを表現していますが、 保守性を考えると共通化してもいいのかなと思います。 難しかったら必須とはしません！
> 
> ![image](https://user-images.githubusercontent.com/83479175/212541905-36685f22-fbf5-4fb8-acc7-26e0246961a3.png)
> 
> ![image](https://user-images.githubusercontent.com/83479175/212541914-8339e86d-786e-4f53-bfe2-71165cb677f7.png)
> 
> 上現在、下figmaです。 xl時、右端の余白が大きすぎる気がするので確認お願いします 🙌

修正しました!

7a5148e84b77961343352a88de7c2d6fbd6800ac

2023-01-22 13:04 UTC, higashiji2000 approved these changes
LGTMです 🥗

2023-01-22 13:04 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +}
単に要素セレクタを使うとサイト内全部の `button` 要素に適用されてしまうので、このような記述は _reset.css の中にまとめるとより良いと思います！（思わぬ箇所に影響が出ること防止の観点）

2023-01-22 13:55 UTC, Hikari-Tanaka-pikka commented on src/components/organisms/header/header.scss
> +}
@higashiji2000 
修正しました

e993961abcee4829415eb3322a3d8cc6812a59ec

2023-01-22 13:57 UTC, merged